### ISSUE TITLE
Neuro-Symbolic Reasoner

### ISSUE THREAD

**Issue by PolKul** [IBM/transition-amr-parser#10]
I was able to train the model as per your instructions. But my ultimate goal is to be able to build a Neuro-Symbolic Reasoning system similar to [this](https://arxiv.org/pdf/2012.01707.pdf) Currently I have the "Semantic Parsing" part of the system working. But I still need to get a "Reasoning" part (namely AMR-to-logic and Logical Neural Networks). Any information about them (or links to the repositories) would be greatly appreciated.

**Comment by ramon-astudillo** [comment]
Please contact first author of that paper for details. Here we only provide the AMr parser used for that work, thanks.
