### ISSUE TITLE
Failed installed and "Needs linking cache DATA/EL/legacy_linker"

### ISSUE THREAD

**Issue by clement1234567891011** [IBM/transition-amr-parser#22]
Hi,

When checking if correctly installed, it says failed installing although it's not very clear to me why. The hint being: "maybe LD_LIBRARY_PATH unconfigured?" (see attached). I've also downloaded manually spacy 2.0.16 thinking from this post that this could help but it did not https://github.com/IBM/transition-amr-parser/issues/13

When running the test file, I also encounter another error: "Needs linking cache DATA/EL/legacy_linker_amr3.0/". Is there a file missing? 
<img width="705" alt="Bildschirmfoto 2022-02-09 um 17 25 31" src="https://user-images.githubusercontent.com/99350729/153246036-c8c62bf0-d5ff-43c1-8efd-ae15396c8c2e.png">

Many thanks in advance for any help!
Best wishes

**Comment by ramon-astudillo** [comment]
> When checking if correctly installed, it says failed installing although it's not very clear to me why. The hint being: "maybe LD_LIBRARY_PATH unconfigured?" (see attached)

the message is misleading, this just means that pytorch-scatter is not installed or failed to install. Try installing manually as indicated in the README

>When running the test file, I also encounter another error: "Needs linking cache DATA/EL/legacy_linker_amr3.0/". Is there a file missing?

See https://github.com/IBM/transition-amr-parser/issues/17 for this

**Comment by clement1234567891011** [comment]
Thanks. With the file, minimal_test now runs up to a point and then crashes with:
<img width="1132" alt="Bildschirmfoto 2022-02-09 um 22 47 40" src="https://user-images.githubusercontent.com/99350729/153295720-4cffcaa8-de61-4bdc-9029-0be3cd4937a1.png">

fairseq 0.10.2 is installed. Anything I can do?

Re correctly_installed: it did not help that I manually installed pytorch_scatter. Still exactly the same message.

Many thanks!

**Comment by ramon-astudillo** [comment]
Did you follow the README install instructions? I find odd that fairseq_ext is installed inside of you pyenv, should be locally on the folder. Can you post the output of
```
bash tests/correctly_installed.sh
```
?

**Comment by clement1234567891011** [comment]
I did: again, pytorch 1.4, and fairseq 0.10.2. Here is the output, same as before...


pytorch 1.4.0
No CUDA available
pytorch-scatter installed
maybe LD_LIBRARY_PATH unconfigured?, import torch_scatter.scatter_cuda dies
fairseq works
[FAILED] installing

**Comment by clement1234567891011** [comment]
I thought that it might have come from me using python 3.8. So, I installed python 3.6, reinstalled the 2 packages pytorch and fairseq, and I still get exactly the same error messages both on the correctly_installed.sh and minimal_test.sh

Any other ideas? Many thanks in advance!

**Comment by clement1234567891011** [comment]
> Did you follow the README install instructions? I find odd that fairseq_ext is installed inside of you pyenv, should be locally on the folder. Can you post the output of
> 
> ```
> bash tests/correctly_installed.sh
> ```
> 
> ?

So, you think that I should install it differently? Or copy it into another folder? Where to?

**Comment by ramon-astudillo** [comment]
> maybe LD_LIBRARY_PATH unconfigured?, import torch_scatter.scatter_cuda dies

you can safely ignore this, since you are installing for GPU. This means that the install was successful. We will change this.

I think I found the problem, please try to install again (new virtualenv) but this time install as editable.

```
pip install --editable .
```

**Comment by clement1234567891011** [comment]
Thanks, it now goes much further but still shoots up up yet another error message about torch not being compiled with CUDA. I'm on OS X 11.6.2, so not sure whether I can install CUDA at all
<img width="936" alt="Bildschirmfoto 2022-02-11 um 14 15 18" src="https://user-images.githubusercontent.com/99350729/153597970-c6f51fd4-d8b8-4bc9-96c1-728df5de2a78.png">
.

**Comment by logicReasoner** [comment]
@clement1234567891011 have you managed to run it without CUDA, using the CPU only?

**Comment by clement1234567891011** [comment]
No, I didn't so far (but may try again later on another non-mac computer where this very issue at least shouldn't crop up)

**Comment by ramon-astudillo** [comment]
Latest version should run on CPU on OSX
