### ISSUE TITLE
Where does entity_rules.json get generated?

### ISSUE THREAD

**Issue by nupoorgandhi** [IBM/transition-amr-parser#24]
I trained a model according to the instructions, and it seems like there was a file entity_rules.json that was supposed to be generated. It looks like these rules are necessary for post-processing, but I am really confused about where in the preprocessing/training code the file gets created.

**Comment by ramon-astudillo** [comment]
this should not be needed for the recent parsers, which version are you using?

**Comment by ramon-astudillo** [comment]
closed due to lack of activity
