### ISSUE TITLE
Instruction of Successfully Installing JAMR for obtaining Alignment

### ISSUE THREAD

**Issue by DreamerDeo** [IBM/transition-amr-parser#25]
The original JAMR was installed in 2015 or 2016 in the server, thus some packages were broken or not updated. The default setup script in JAMR repos is set to a version no longer available.
I have pushed a new [JAMR repos](https://github.com/DreamerDeo/JAMR) to deal with this issue. More details on https://github.com/jflanigan/jamr/issues/44.

The most important part is to install the updated version of scala and sbt.
To manually install them, you can use [SDKMAN!](https://sdkman.io/install) and run the following:
>     sdk install sbt 1.0.2
>     sdk install scala 2.11.12

And then you could replace **https://github.com/IBM/transition-amr-parser/blob/dfd8352ea2ee3ff153b691edb6cd7ee541d53b2e/preprocess/install_alignment_tools.sh#L13** with `https://github.com/DreamerDeo/JAMR.git` , where the scala version are clarified in some config files.
(of course, you could also clone the original JAMR repos and do this manually)

**Comment by ramon-astudillo** [comment]
thanks! with https://github.com/IBM/transition-amr-parser/releases/tag/v0.5.2 we are deprecating the JAMR aligner in favour of the ibm-neural-aligner. We can make the JAMR alignments available via the same mechanism as the checkpoints.
