### ISSUE TITLE
How to use this parser on other languages

### ISSUE THREAD

**Issue by WDZRMPCBIT** [IBM/transition-amr-parser#26]
I want to use this Parser with Chinese Dataset, and try to use mbart(https://github.com/pytorch/fairseq/tree/main/examples/mbart). But the difference of data preprocess and encode/decode makes it hard to use this parser with Chinese. How can I do that?

**Comment by xxllp** [comment]
+1

**Comment by ramon-astudillo** [comment]
we will release a `structured-mbart` branch next week, check https://twitter.com/RamonAstudill12/ for updates

**Comment by ramon-astudillo** [comment]
@WDZRMPCBIT @xxllp see https://github.com/IBM/transition-amr-parser/tree/structured-mbart

**Comment by pournaki** [comment]
I am using the code from your README to parse EN sentences: 
https://github.com/IBM/transition-amr-parser?tab=readme-ov-file#parse-with-a-pretrained-model

Is there a straightforward way to adapt it for parsing the other available languages using one of your pre-trained models?
