### ISSUE TITLE
Did you release the code of (Drozdov et al 2022) ?

### ISSUE THREAD

**Issue by xsthunder** [IBM/transition-amr-parser#31]
Thanks for releasing the code. It's very helpful. However I've having trouble in finding the code mentioned in [(Drozdov et al 2022)](https://arxiv.org/abs/2205.01464).

I've carefully looked into the `README.md` of four branches [structured-mbart](https://github.com/IBM/transition-amr-parser/tree/structured-mbart), [action-pointer](https://github.com/IBM/transition-amr-parser/tree/action-pointer), [stack-transformer](https://github.com/IBM/transition-amr-parser/tree/stack-transformer) as well as the master branch, but none of them contains the instructions for [(Drozdov et al 2022)](https://arxiv.org/abs/2205.01464). Did you the code of (Drozdov et al 2022)?  I would be very grateful if you could help me find it.

Thank you for your time to this matter.

**Comment by ramon-astudillo** [comment]
yes, check 

    configs/wiki25-structured-bart-base-neur-al-sampling5.sh

for a sanity check experiment with a few sentences(wont learn) and the equivalent amr2/3 configs.
