### ISSUE TITLE
Please publish this on PyPI

### ISSUE THREAD

**Issue by chanind** [IBM/transition-amr-parser#35]
This is the current state of the art for AMR parsing, but it's still difficult to integrate into other projects that require AMR parsing since it's not a published module and is built with the assumption that it's just a code demo, rather than a tool to be used to parse AMR. But it looks like it's very close to being able to be publishable, e.g. it has a setup.py that looks correct. I think it just needs to remove the debugger from being always activated by default and it should work as a PyPI module.

If this was published as a PyPI module it would help push the whole AMR field forward, and I'm sure it would result in more citations for your papers too since then others can easily use it in further projects, rather than needing to fall back on easier-to-run but less powerful parsers for AMR like amrlib.

**Comment by ramon-astudillo** [comment]
Thanks for pointing out the debug mode issue @chanind, I have removed it in this commit c9bf86bd300eefa23b5a31912dc1365b59cda094.

Regarding PyPI, this will still take some time (we may have updates in Q1). In the meanwhile a local install i.e.

```
git clone ...
pip install -e transtition-amr-parser
``` 

Should work to integrate it into other projects. This also makes sense given the way we provide trained checkpoints right now (DATA folder). 

Note that for user installs we also provide a Docker and an endpoint which is what other teams use at IBM.

**Comment by ramon-astudillo** [comment]
this is now available, see README.md @chanind
