### ISSUE TITLE
Question about cloning

### ISSUE THREAD

**Issue by antonlabate** [IBM/transition-amr-parser#41]
Hi!

I have tried to clone the repository as in the README.md (git clone git@github.ibm.com:mnlp/transition-amr-parser.git), but as response I always get 
_git@github.ibm.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists._

Already added a ssh key to my git account to give me authorization and tested it through ssh -T git@github.com. Nonetheless, I still have the same problem when trying to clone the repository (even through https). Any suggestion on how to solve it?

Thanks,
Anton

**Comment by sadhana01** [comment]
Please try 
`git clone git@github.com:IBM/transition-amr-parser.git`

**Comment by antonlabate** [comment]
Worked!
Thanks,
