### ISSUE TITLE
I want to learn how to construct a AMR Parser by myself 

### ISSUE THREAD

**Issue by ShaoZhangHao** [IBM/transition-amr-parser#45]
Excuse me， I need your help. I want to learn how to construct a AMR Parser，so I reading many papers，I still can not unterstand what  the papers express ，even the algorithm.Thus，Do you have any books or papers introduced ？I am new to this kind of work.

**Comment by ramon-astudillo** [comment]
Have a look at the papers in the README and the SPRING paper cited there may also be an easy way to start.
