### ISSUE TITLE
j>i?

### ISSUE THREAD

**Issue by Zoher15** [IBM/transition-amr-parser#51]
https://github.com/IBM/transition-amr-parser/blob/849b1ee69370240c423cb987a02103693c951027/scripts/mbse.py#L300

Hello,

I was wondering why this above line is different from line 284? Isn't this doing redundant calculations? Or am I understanding something wrong?

Best,
Zoher

**Comment by ramon-astudillo** [comment]
Yes, but that operation has no cost so it's irrelevant.
